[workspace]
resolver = "2"
members = ["bpers"]
dependencies = { indexmap = "2.9.0", foldhash = "0.1.5" }

[package]
name = "bpe"
version = "0.1.0"
edition = "2024"

[dependencies]
bpers = { path = "bpers" }
clap = { version = "4.5.35", features = ["derive"] }
